// src/app/index.tsx — Home: search the bundled hero list
import { Href, Link, router, Stack } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { searchHero, targetSummary } from "../logic/resolveMedicine";
import type { Medicine } from "../types";

const QUICK = [
  { id: "ibuprofen", label: "Ibuprofen" },
  { id: "aspirin", label: "Aspirin" },
  { id: "atorvastatin", label: "Atorvastatin" },
  { id: "acetaminophen", label: "Acetaminophen" },
];

// Typed routes are regenerated by `expo start`; cast until the generated types include these screens.
const openMedicine = (id: string) => router.push(`/medicine/${id}` as Href);

export default function Home() {
  const [query, setQuery] = useState("");
  const results = searchHero(query);
  const searching = query.trim().length > 0;

  return (
    <SafeAreaView style={s.page} edges={["top", "bottom"]}>
      <Stack.Screen options={{ headerShown: false }} />
      <FlatList
        data={results}
        keyExtractor={(m) => m.id}
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={s.content}
        ListHeaderComponent={
          <View style={s.header}>
            <Text style={s.title}>MoleculeLens Rx</Text>
            <Text style={s.sub}>See your medicine inside the protein it acts on</Text>
            <TextInput
              style={s.input}
              value={query}
              onChangeText={setQuery}
              placeholder="Search a medicine, e.g. ibuprofen or Advil"
              placeholderTextColor="#6b7599"
              autoCapitalize="none"
              autoCorrect={false}
              clearButtonMode="while-editing"
              returnKeyType="search"
            />
            <Pressable style={s.scanBtn} onPress={() => router.push("/scan" as Href)}>
              <Text style={s.scanText}>📷 Scan a box</Text>
            </Pressable>
          </View>
        }
        renderItem={({ item }) => <ResultRow med={item} />}
        ListEmptyComponent={
          searching ? (
            <Text style={s.empty}>No match in the MoleculeLens list yet. Try a generic name like “naproxen”.</Text>
          ) : null
        }
        ListFooterComponent={
          <View style={s.footerBlock}>
            {!searching && (
              <View style={s.chips}>
                {QUICK.map((q) => (
                  <Pressable key={q.id} style={s.chip} onPress={() => openMedicine(q.id)}>
                    <Text style={s.chipText}>{q.label}</Text>
                  </Pressable>
                ))}
              </View>
            )}
            <View style={s.links}>
              <Link href={"/cabinet" as Href} style={s.link}>My cabinet →</Link>
              <Link href="/paywall" style={s.link}>Lens Pro →</Link>
            </View>
            <Text style={s.footer}>Educational only · not medical advice</Text>
          </View>
        }
      />
    </SafeAreaView>
  );
}

function ResultRow({ med }: { med: Medicine }) {
  return (
    <Pressable style={({ pressed }) => [s.row, pressed && { opacity: 0.7 }]} onPress={() => openMedicine(med.id)}>
      <Text style={s.rowTitle}>{med.name}</Text>
      {med.brandNames.length > 0 && <Text style={s.rowBrands}>{med.brandNames.join(", ")}</Text>}
      <Text style={s.rowTarget}>{targetSummary(med)}</Text>
    </Pressable>
  );
}

const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#05070f" },
  content: { padding: 16, gap: 10 },
  header: { gap: 8, marginBottom: 6 },
  title: { color: "white", fontSize: 28, fontWeight: "800", marginTop: 12 },
  sub: { color: "#9aa4c7", fontSize: 15 },
  input: {
    marginTop: 12, backgroundColor: "#111833", color: "white", fontSize: 16,
    paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: "#22306b",
  },
  scanBtn: { backgroundColor: "#22306b", paddingVertical: 12, borderRadius: 12, alignItems: "center" },
  scanText: { color: "white", fontSize: 16, fontWeight: "600" },
  row: { backgroundColor: "#111833", padding: 14, borderRadius: 12, gap: 2 },
  rowTitle: { color: "white", fontSize: 17, fontWeight: "600" },
  rowBrands: { color: "#9aa4c7", fontSize: 13 },
  rowTarget: { color: "#9fb4ff", fontSize: 13, marginTop: 2 },
  empty: { color: "#9aa4c7", textAlign: "center", padding: 16 },
  footerBlock: { gap: 16, marginTop: 8 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { backgroundColor: "#22306b", paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999 },
  chipText: { color: "white", fontWeight: "600" },
  links: { flexDirection: "row", justifyContent: "space-around", marginTop: 8 },
  link: { color: "#9fb4ff", fontSize: 16, padding: 8 },
  footer: { color: "#6b7599", fontSize: 12, textAlign: "center", marginTop: 8 },
});
